### ISSUE TITLE
Explore mutants before being tested

### ISSUE THREAD

**Issue by ocornejo** [joakim-brannstrom/dextool#1007]
Hello, I have two questions:

*  Does necessarily dextool needs to compile the software under test with clang for identifying mutants?
*  After running the command ```dextool mutate analyze```, is there a way to explore the mutants identified by dextool? Before being executed through the test suite?

Thanks in advance

**Comment by christoffer-nylen** [comment]
Hi,

Thank you for your question! I will try to answer it.

>Does necessarily dextool needs to compile the software under test with clang for identifying mutants?

Dextool uses libclang to identify possible mutants, but it does not use clang to compile anything, that part is instead managed by scripts provided by the user.

The user provides:
* `build.sh` - that is responsible for compiling the software under test (using any compiler).
* `test.sh` - that is responsible for compiling the test code and linking the test binaries (using any compiler).

During the `dextool mutate test` phase, dextool:
* Inserts mutants into the source code textually.
* Invokes `build.sh` to compile the software under test.
* Invokes `test.sh` to compile the test code, link the test binaries and run the tests.

>After running the command dextool mutate analyze, is there a way to explore the mutants identified by dextool? Before being executed through the test suite?

Yes, you can generate a report at any time (before, during and after). Personally, I prefer to use the html report variant, for example `dextool mutate report --style html`. You can explore other variants, more information about report can be found in [options.md](https://github.com/joakim-brannstrom/dextool/blob/master/plugin/mutate/doc/design/options.md#report) or `dextool mutate report -h`. I think this use case is very common, I will try to update `readme.md` to reflect it better.

Feel free to ask more questions.

**Comment by joakim-brannstrom-work1** [comment]
Hello @ocornejo ,

The semantic information from the compiler is used to identify "actually", useful mutants. This unfortunately mean that dextool, via libclang, has to practically *compile* the source code to be able to access the AST. For a large project I can understand that this is perceived as slow when analyzing. But in comparison this means that the test phase is faster. As an example of our internal testing it reduced the number of mutants for ROR by 50% by removing all "junk". For us it moved ROR from being practically useless to "now it is a contented for inclusion in our recommended operators".

We are working on some features to alleviate this by making it possible to integrate in pull request workflow. One of them is to make it possible to analyze/test/report only those files that has been changed.

**Comment by joakim-brannstrom** [comment]
Please open the issue if you need more help.

    We are working on some features to alleviate this by making it possible to integrate in pull request workflow. One of them is to make it possible to analyze/test/report only those files that has been changed.

This has been integrated via --diff-from-stdin
