### ISSUE TITLE
Add newline to EOF after "modified by dextool" notice

### ISSUE THREAD

**Issue by pokgak** [joakim-brannstrom/dextool#1161]
My project is configured to return error during compiling if the source code doesn't have newline at EOF. So when using `dextool mutate generate --id <id>` to test manually, I got the error and had to add the newline manually each time. 

I'm not sure if this also affects the overall test when using `dextool mutate test`, but currenty I have a lot of `unknown` status for the tests. 

Example:
```
info: Using /home/pokgak/git/RIOT-mutate/mutate/dextool_mutate.sqlite3
info: Summary
Time spent:  3 minutes, 22 secs, and 832 ms
Remaining: 1 hour, 5 minutes, 31 secs, 820 ms, and 298 μs (2020-08-15T17:08:42.0288293)

Score:       0.846
Total:       13
Untested:    252
Alive:       2
Killed:      11
Timeout:     0
Killed by compiler: 0
```

**Comment by joakim-brannstrom** [comment]
Thank you for the issue. You mean the text "/* DEXTOOL: THIS FILE IS MUTATED */" ? :)
If so the pull request above should fix it.

**Comment by joakim-brannstrom** [comment]
Keep on reporting issues as you find them. The intent is for the tool to be usable :)

**Comment by pokgak** [comment]
Thank you for the fast response. I'll test this locally and report back later :)

**Comment by pokgak** [comment]
Confirmed solve using the latest master.
