### ISSUE TITLE
mutate: absZero fail_on_zero_dextool should not mutate function returning void

### ISSUE THREAD

**Issue by pokgak** [joakim-brannstrom/dextool#1167]
The absZero mutant currently applies the `fail_on_zero_dextool` macro as a bomb when the function returns zero. For functions that return `void` this is meaningless as it will always be true (not zero) in any condition.

Example:

```C
// declaration of mutex_lock()  [1]
static void mutex_lock(mutex_t *mutex);

// original code  [2]
mutex_lock(&mutex);

// mutated code  [3]
fail_on_zero_dextool(mutex_lock)(&mutex);

// code mutated directly instead of using the fail_on_zero macro  [4]
(!mutex_lock && (*((char*)0) = 'x') ? mutex_lock : mutex_lock)(&mutex);
```

With `-Wpointer-bool-conversion` flag enabled, the compiler detects this in [4] and this mutant will be killed but I'm not sure why in [3] the compiler does not detect this. In my codebase this should eliminate a number of alive mutants.

**Comment by pokgak** [comment]
might be related to #917

**Comment by joakim-brannstrom** [comment]
the ABS mutant hasn't, honestly, been a priority to "fix" because the others have provided "enough" value :). Enough mutants to "handle"... :)
Last time I looked at the ABS mutant I think >40% of the mutants where undesired.

**Comment by joakim-brannstrom** [comment]
Your report though is pretty clear with what is the problem and the Clang AST have all the information so should be pretty easy to fix this case.

**Comment by pokgak** [comment]
I'm currently using the default mutant operators and so far the mutants are reasonable, so I'll just stick to that for now.

**Comment by joakim-brannstrom** [comment]
With #1273 the mutation operator ABS has been removed.
