### ISSUE TITLE
Sucessfully building dextool but not plugins are available

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#1169]
Hiya! 

I managed to build dextool, and it seems that I got the plugins. 
However, when executing **dextool** I ran into issues. 

```
bin$ ./dextool
error: No plugin specified
Available plugins:
-h for further help
error: exiting...
```

I do however have all plugins it seems as binaries. Is this a known issue? 

Sorry for confusing language..  

Cheers,
John

**Comment by joakim-brannstrom** [comment]
hi,

I think #1171 will solve it.

The implementation of `which`, specifically [this line](https://github.com/joakim-brannstrom/dextool/blob/81dd374bf7a3270e0202ccba1d8acdb4d9ec2c16/vendor/mylib/source/my/file.d#L207) could throw an exception if any of the directories scanned weren't readable by the user. I found this out in another project thus I wanted to add that fix and some others to dextool yesterday :)

**Comment by JKRT** [comment]
Hi,

Will test and get back to you

Cheers,
John

**Comment by joakim-brannstrom** [comment]
I assume that it works for you now. Please open the issue if it still persist.
I haven't noticed this problem myself thus...
