### ISSUE TITLE
TDDD04

### ISSUE THREAD

**Issue by della-123** [joakim-brannstrom/dextool#1192]
Getting the following issue when I running it inside the build folder.

/Desktop/TDDD04/dextool/build$ cmake -DCMAKE_INSTALL_PREFIX=. -DD_COMPILER=/opt/dmd/2.088/linux/bin64/dmd
CMake Error: The source directory "/home/delba753/Desktop/TDDD04/dextool/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by joakim-brannstrom** [comment]
This is a cmake problem. You where missing the path to where CMakeLists.txt is.

```sh
cmake -DCMAKE_INSTALL_PREFIX=. -DD_COMPILER=/opt/dmd/2.088/linux/bin64/dmd ..
```
note the trailing ".."
