### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by della-123** [joakim-brannstrom/dextool#1193]
Getting the following error when trying to run mutation testing.

/TDDD04/dextool$ dextool mutate test --mutant lcr --mutant lcrb
info: Using /home/Desktop/TDDD04/dextool/dextool_mutate.sqlite3
info: Sanity check passed. Files on the filesystem are consistent
info: Preparing for mutation testing by checking that the program and tests compile without any errors (no mutants injected)
**error: Failed to execute program (Permission denied)**
info: Done! All mutants are tested

**Comment by joakim-brannstrom** [comment]
Please open the issue if it still persist. I assume that the lab assistant have helped you.
For me to solve this I would need to be able to reproduce it at my side. I think your problem is that whatever was built was missing the execution bit on the executable.
