### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by joakim-brannstrom** [joakim-brannstrom/dextool#1226]
**Problem**

The current documentation is lacking in:

- [x] how to use mutation testing for CI (mutate a git diff). Everything is implemented for it just not documented **here**. In other words that dextool can read a patch and only mutate the mutants that are in the patch. Perfect for pull request integration.
- [x] the report sections.
- [x] recommendations for how to use mutation testing in by a team together with configuration examples, CI etc. This is partly also how to work long term with mutation testing.
- [ ] what mutation schemata is and how this makes dextool *different* from simple source code mutators. There may be a misconception that dextool mutate is one of these.
- [x] explain the mutation operators, which ones to use and why. also what they *mean*.
- [x] document how to use a custom testing framework. the support exists just hasn't been documented properly.
- [x] how to use dextool mutate for mutation testing of embedded systems. It has been developed with this feature in mind so should document it properly.
- [ ] document supported platforms. Linux, MacOS? and windows under WSL.

**Comment by Warwolt** [comment]
Unless I'm mistaken then documentation of how one is meant to actually _aquire_ Dextool Mutate is missing as well. I found some instructions [here](https://www.ida.liu.se/~TDDD04/labs/2019/mutation_testing/) on the LIU website, but on this repository there only seem to be instructions on using Mutate, not building or installing it.

**Comment by joakim-brannstrom** [comment]
I'll take it as a hint that it can be improved :+1:

**Comment by joakim-brannstrom** [comment]
Solving some of them in  #1243
