### ISSUE TITLE
introspect_llvm.d returns llvm-config-9 when it should return llvm-config-11

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#1482]
Hi, 

This is an issue in version 1.3.2 of dextool. It might have been resolved in future versions. 
I have the following variants of llvm-config:
`llvm-config     llvm-config-10  llvm-config-11  llvm-config-9   `

and llvm-config is set to 11

However, when introspect_llvm.d runs it seems that it always returns llvm-config-9 
(What I would like it to select is 11 or 10)

Is this something that is fixed in later variants of dextool, would it be possible to backport 1.3.2 (The LiU release)? 

I fixed the issue by just changing line 185 to llvm-config-10 (but I would have expected it to return a more recent version (Something with the sorting?))

Cheers,
John

**Comment by joakim-brannstrom** [comment]
Ping me tomorrow and I'll paste here what you can do to completely control it yourself. I think that is the easiest in this case and version 1.3.2 already support it.

Note though that the clang-API is not 100% backward/forward compatible. I noticed for example that master do not build with clang-13. Something, something with the c++ API has changed.

**Comment by JKRT** [comment]
@joakim-brannstrom Thanks! will do so:)

**Comment by JKRT** [comment]
@joakim-brannstrom  Ping!

**Comment by joakim-brannstrom-work1** [comment]
@JKRT I have created #1483 with instructions of how to manually pass on flags that are otherwise derived from llvm-config. I would recommend that you try to follow the instructions. Ping me if they do not work :)

**Comment by joakim-brannstrom** [comment]
I consider it solved with #1483 and #1484 (some fixes to the readme). #1486 updates the docker image as we talked about.
