### ISSUE TITLE
Outdated Dockerfile and not able to compile when trying to update it

### ISSUE THREAD

**Issue by jakobsjoqvist** [joakim-brannstrom/dextool#1485]
Hi,

As the title states, the Dockerfile in `Docker/dextool-ubuntu-xenial` is outdated and the image cannot be built. I have tried to create a new Dockerfile based on the previous one combined with the installation instructions for Ubuntu but when I try to build the image it fails to compile the project.

My Dockerfile:
```
FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
    build-essential \
    cmake \
    llvm-12 \
    llvm-12-dev \
    clang-12 \
    libclang-12-dev \
    libsqlite3-dev \
    git \
    ca-certificates \
    wget

WORKDIR /opt

RUN wget https://github.com/ldc-developers/ldc/releases/download/v1.27.1/ldc2-1.27.1-linux-x86_64.tar.xz && \
    mkdir -p /opt/dlang && \
    tar -xf ldc2-1.27.1-linux-x86_64.tar.xz -C /opt/dlang
 ENV PATH "/opt/dlang/ldc2-1.27.1-linux-x86_64/bin:$PATH"

RUN git clone --depth 1 https://github.com/joakim-brannstrom/dextool.git

RUN mkdir dextool/build && cd dextool/build && \
    cmake -DCMAKE_INSTALL_PREFIX=/opt/dextool/build .. && \
    make install
```

I have tried to install version 10 of llvm, clang and libclang but it does not help.

Error:
```
Error: Error executing /opt/dlang/ldc2-1.27.1-linux-x86_64/bin/ldc2: Killed
make[2]: *** [plugin/mutate/CMakeFiles/dextool-mutate.dir/build.make:120: plugin/mutate/dextool-mutate.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1635: plugin/mutate/CMakeFiles/dextool-mutate.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

Please advise how I can run it in Docker :)

Thanks in advance!

**Comment by joakim-brannstrom** [comment]
hi, thank you for the issue. I'll update the image to focal in #1486 

But the killed hmm, I think it consumed all your RAM. It needs 16Gbyte to comfortably build.

**Comment by joakim-brannstrom** [comment]
I'm adding the -DLOW_MEM=ON to the dockerfile, just in case :)

**Comment by jakobsjoqvist** [comment]
Thanks for the fast reply (and fix :) )!

Just to update, I tried to build the updated Docker image but I still get the same error, I will try to restart my computer and see if that helps, however the issue might be that only have 16GB RAM in total. If you can build the image on your system I think it works as it should and this issue can be closed :)

**Comment by joakim-brannstrom** [comment]
Nice idea. I have been experimenting a bit today. I've created and uploaded an image so it is easier to use. I'll improve it in the future. Do you think this is good enough for your tests of dextool?

```
FROM joakimbse/dextool-ubuntu

WORKDIR /opt
ENV PATH "/opt/dextool_install/bin:$PATH"
```
