### ISSUE TITLE
`dextool mutate analyze` hangs if there is only one CPU core available

### ISSUE THREAD

**Issue by bluescreen-erg** [joakim-brannstrom/dextool#1554]
When running `dextool mutate analyze` in a VM (Ubuntu 22.4) with only one CPU core assigned to it, the execution hangs. No error message or warning is shown. 

Running the same command in the same project, but with four CPU cores assigned to the VM causes the analysis to complete successfully. 

I propose to add a warning message if system has not enough cores assigned to it. 

I tried this with version v4.2.0 of dextool.

**Comment by joakim-brannstrom** [comment]
Ohh thanks for the bug report. Guess I've never tried with one core. Will fix

**Comment by joakim-brannstrom** [comment]
Added a workaround in master with #1555 and #1557. i'll try to make a formal release this weekend.
