### ISSUE TITLE
Failed to build the project in arch linux

### ISSUE THREAD

**Issue by chengjackjelly** [joakim-brannstrom/dextool#1738]
### Type of Issue
_Please check the type of your issue by marking it with an `x`._

- [x] Bug Report
- [ ] Feature Request
- [ ] General Feedback/Question

---

**Operating System:**
- OS: OS: Arch Linux x86_64 
- Kernel Version: OS: Arch Linux x86_64 

**Clang :**
```
clang version 18.1.8
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```
#### Description

This is the error report when I try to run the ```make install``` in my archlinux

![image](https://github.com/user-attachments/assets/f90513f1-be04-4663-a511-8f552aa2883d)

This indicated that I don't have these clang libraries in my usr/lib, although I have my clang installed. After asking for help in arch linux sub reddit, I got a very valuable help from other user: [post](https://www.reddit.com/r/archlinux/comments/1fwobza/comment/lqgtyd6/)

I followed the provided patch in this post to modify `instrospect_llvm.d` and installed dextool successfully.

The reason also provided in post, which is because the current packaging method for clang in archlinux bundled all these libraries into clang-cpp.so.

**Comment by chengjackjelly** [comment]
I also provided a patch and hopefully will submit a pr to it later

**Comment by joakim-brannstrom** [comment]
Thank you for informing me of the problem and providing a patch. It made it a lot easier to working on a fix. I've taken your PR and further tweaked it to work on Ubuntu too.
