### ISSUE TITLE
Missing multiple parameters in Et (dsrcgen)

### ISSUE THREAD

**Issue by ploq** [joakim-brannstrom/dextool#317]
Multiple parameters for Et is not implemented (afaik).
At the moment one would need to create a string with all the parameters, would be better if Et takes an array (or something like an array) with strings.

For example:
`Et("Some_template")("param1, param2")` is what is required now.
What I am proposing: `Et("Some_template")("param1", "param2")`

**Comment by joakim-brannstrom** [comment]
I'lll leave the issue open until you have had time to try the fix :)

**Comment by ploq** [comment]
Yup, the fix seems to work!
