### ISSUE TITLE
func_body args should be able to handle CxParam[]

### ISSUE THREAD

**Issue by ploq** [joakim-brannstrom/dextool#318]
func_body args (dsrcgen) should be able to handle a CxParam[] since that is what CFunction is returning.

**Comment by ploq** [comment]
On another note, OpCall should be defined for func_body for the arguments for consistency with E().

**Comment by joakim-brannstrom** [comment]
Handling CxParam[] in dsrcgen would be problematic. It would create a dependency dsrcgen -> cpptooling. Dsrcgen is intended to be a freestanding library.
But for this purpose the helper functions joinParams and joinParamNames in cpptooling.data.representation may help?

**Comment by ploq** [comment]
Ah, of course... Missed that one. 
Yeah, those functions works just as good!

**Comment by joakim-brannstrom** [comment]
Implementing opCall for func_body would require a redesign as-is.
But I see what you mean. It would be more "natural".
Let me think.
