### ISSUE TITLE
forward reference to splitTypeId

### ISSUE THREAD

**Issue by ploq** [joakim-brannstrom/dextool#325]
Seems to be a forward reference to splitTypeId in cpptooling.analyzer.type. 
Fixed it by moving `splitTypeId(ref const TypeKind t)` before `splitTypeId(ref const TypeKind t, const uint indent = 0)`

**Comment by joakim-brannstrom** [comment]
I see. Could it have something to do with an older compiler?
Either way, fixing as you said in #326

**Comment by ploq** [comment]
Yes probably, I am using 2.070.2. Should probably update it to the latest

**Comment by joakim-brannstrom** [comment]
Probably because it was the requirement when doing the group assignment. But I've raised the minimum req. to 2.071.2 since then. Keeping in sync with LDC

**Comment by ploq** [comment]
Ahh! Seems to be working now :)
