### ISSUE TITLE
isysroot should be threated as an include path

### ISSUE THREAD

**Issue by ploq** [joakim-brannstrom/dextool#338]
-isysroot is a Mac specific argument to clang that says where the system files are (/usr/include etc.) 
Unlike -I it has a space after -isysroot and then comes the path. Which makes compilation_db.d think it just is a flag without any parameters. 

Without it, Clang can't compile since it does not know where the system headers etc. are. 

Suggested fix for compilation_db.d in parseFlag:
```
        foreach (arg; r) {
            if (st == State.skip) {
                st = State.keep;
            } else if (st == State.skipIfNotFlag && isNotAFlag(arg)) {
                st = State.keep;
            } else if (st == State.isInclude) {
                st = State.keep;
                // if an include flag make it absolute
                rval.put("-I");
                rval.put(buildNormalizedPath(workdir, arg).absolutePath);
            } else if (isCombindedIncludeFlag(arg)) {
                rval.put("-I");
                rval.put(buildNormalizedPath(workdir, arg[2 .. $]).absolutePath);
            } else if (arg.among("-I")) {
                st = State.isInclude;
            }
            else if (arg.among("-isysroot")) { //This should be added
                st = State.isInclude;
            }
            else if (excludeStartWith(arg, flag_filter)) {
                st = State.skipIfNotFlag;
            } else if (isNotAFlag(arg)) {
                // skipping
            } else {
                rval.put(arg);
            }
        }
```

**Comment by joakim-brannstrom** [comment]
Thank you for the feedback.
Does #339 solve the issue?

**Comment by joakim-brannstrom** [comment]
Thanks for the suggested implementation. I iterated over it a couple of times to arrive on the solution in #339. A more general approach that should be able to be easily expanded in the future.

**Comment by ploq** [comment]
Yes, that seems to do the trick! Awesome, thanks!

**Comment by ploq** [comment]
Something seems to have fixed it on my way home (uhm...), does not matter how I generate the compilation database. But the fix I proposed did the trick when it was not working and with your fix I can see that the internal headers are correct, -isysroot *path* instead of just -isysroot.

**Comment by joakim-brannstrom** [comment]
As I understand it now works, so closing. If it is still an issue please reopen the issue
