### ISSUE TITLE
typedefs gets evaluated a bit to much

### ISSUE THREAD

**Issue by ploq** [joakim-brannstrom/dextool#378]
Input:
```
typedef unsigned int ll;
typedef ll some_array[1];

const some_array& some_func();
```
Generated output:
```
const unsigned int ( &)[1] some_func() const {
 	do_something();
}
```
Expected: 
```
const some_array& some func() {
	do_something();
}
```

**Comment by joakim-brannstrom** [comment]
thank you. This will make it easy to fix :)

**Comment by ploq** [comment]
Jinxed it ;)

**Comment by joakim-brannstrom** [comment]
I am unable to reproduce the error in #379

**Comment by ploq** [comment]
Hmm okay, I will try make some better test code by monday

**Comment by ploq** [comment]
I am unable to reproduce this in my Mac environment but in Ubuntu (clang 3.8.1) I was able to reproduce... 

In one file (foo-bar.hpp): 
```
//include only foo.hpp
namespace Foo { Namespace Bar {
    typedef some_unsigned some;
    typedef some return_val[1];
} }
```

In another file (foo.hpp):
```
namespace Foo {
    typedef unsigned int some_unsigned;
}
```

Header file for function (foo-bar-bla.hpp)
```
//include only foo-bar.hpp
namespace Foo { namespace Bar { namespace Bla {
    class Blabla {
        public: 
            virtual const Foo::Bar::return_val& Do_something() const = 0;
    };
} } }
```
I hope that this is reproducible now...

**Comment by joakim-brannstrom** [comment]
Yes, it is reproducible with clang 3.7. Fixed in #379

**Comment by joakim-brannstrom** [comment]
Thank you for the excellent bug report.

**Comment by ploq** [comment]
Great work! Can confirm that it works!
