### ISSUE TITLE
html: mutant killed by test case

### ISSUE THREAD

**Issue by joakim-brannstrom** [joakim-brannstrom/dextool#867]
Show what test case killed a mutant.

**Comment by joakim-brannstrom** [comment]
When inspecting a surviving mutant in the html code view, the user would like a convenient way to find test cases that killed a “near” mutant. For example if ‘a || b’ -> ‘false’ was killed, but ‘a || b’ -> ‘true’ survived, the user would like to know which test case(s) that killed the first mutation, so that they can use it to assess the surviving mutant (and perhaps extend the test suite to kill the second mutant).
Example suggestion: Add some ‘killed by test case(s): … ’ information box that shows up when the user is hovering the mouse over a mutation point that is killed.

**Comment by christoffer-nylen** [comment]
In a formal verification process, an example use case could look something like this:

> ## How to handle surviving mutants?
>![coverage3](https://user-images.githubusercontent.com/5559216/60397704-ffedb180-9b4f-11e9-83af-84e0cdfe2f74.png)
>
>For high criticality software, suviving mutants of type SDL, DCR, LCR, LCRb must be resolved in one of the following ways:
>1. Remove code
>2. Correct tests
>3. Change/add requirements + tests
>4. Analysis and justification for e.g. defensive programming

**Problem:** For approach **2** and **3** the user would like to find out *how to kill a surviving mutant*.

**Solution:** Present the test cases that killed a “near” mutant, as suggested in previous comments.
