### ISSUE TITLE
The default configuration does not find the installed D-Compiler

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#897]
Hi, 

I have been following the instructions in the readme. 

When executing: 

`CMake Error at cmake/Modules/FindDCompiler.cmake:72 (string):
  string sub-command REGEX, mode MATCH regex "^[^

  :]*" matched an empty string.
Call Stack (most recent call first):
  cmake/CMakeDetermineDCompiler.cmake:2 (include)
  CMakeLists.txt:5 (enable_language)

CMake Error at cmake/Modules/ExtractDMDSystemLinker.cmake:40 (message):
  Failed to compile empty program using D compiler '/opt/dmd/2.088'
Call Stack (most recent call first):
  cmake/Modules/FindDCompiler.cmake:76 (include)
  cmake/CMakeDetermineDCompiler.cmake:2 (include)
  CMakeLists.txt:5 (enable_language)

CMake Error: CMAKE_D_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/myUser/TDDD04/DEXTOOL/dextool/build/CMakeFiles/CMakeOutput.log".
` 
[CMakeOutput.log](https://github.com/joakim-brannstrom/dextool/files/3586778/CMakeOutput.log)

Best regards,

John

**Comment by joakim-brannstrom** [comment]
I think this is the problem:
```
Failed to compile empty program using D compiler '/opt/dmd/2.088'
```

It indicates that the compiler has been set to the directory and not the binary. Is "dmd" or "ldmd2" available in the PATH variable?

Otherwise you can tell cmake what d compiler you want to use:

```
cmake .. -DD_COMPILER=/opt/dmd/2.088/linux64/bin/dmd
```

**Comment by joakim-brannstrom** [comment]
Do you think this will help?
https://github.com/joakim-brannstrom/dextool/pull/899/files

**Comment by peatersson** [comment]
I am taking the liberty to answer for both me and @JKRT: 

Yes, it helped specifying the compiler.
