### ISSUE TITLE
Request to use DMD in azure-pipeline as well as LDC.

### ISSUE THREAD

**Issue by peatersson** [joakim-brannstrom/dextool#898]
Since it is stated in README that dextool support both DMD and LDC, should the CI contain both compilers?

//NP

**Comment by joakim-brannstrom** [comment]
It already do, see [docker test](https://github.com/joakim-brannstrom/dextool/blob/f9d177617399f9bdfcf52dad76c6ff51f3c69438/Docker/docker.d#L70)
