### ISSUE TITLE
Lab for Liu

### ISSUE THREAD

**Issue by joakim-brannstrom** [joakim-brannstrom/dextool#903]
Develop a lab for LIU where mutation testing is used to teach students about the concept and pitfalls.
The lab should be about 6h in total. 2h lecture + 4h lab.

The lab should contain the following:
- [x] a medium complex project
- [x] basic tests suite that the students can extend
- [x] assignments

Lecture:
- demonstrate that you do not need many test cases to get *high* coverage but that this coverage do not tell you anything about the test suite quality when it comes to verifying the functionality. This is a common problem in industry.
    - [x] integrate gcov + lcov for a coverage report.

[TDDD04](https://www.ida.liu.se/~TDDD04/labs/2018/unit_testing/)

> From part 2, you need to provide your test cases, along with a coverage report and a screenshot showing that there are no surviving mutants, or a good justification of why the mutants are equivalent to the original program to justify that you have passed the assignment.
Lab content based on the above description and extended:
- the student should extend the test suite 5 times to kill new mutants.
    - each time it is extended they must provide a new rationale for why they do it.
    - each extension should result in an improved mutation test score.
- they should for each mutant explain why they chose to kill it. This should be five different reasons based on:
    - existing test suite already kills a mutant close to it
    - the test suite has coverage for the location
    - the test suite has no coverage
    - adding a new check to an existing test case
- the student should reason about what is a good test case based on those that they have implemented:
    - how the test case is implemented
    - the specific mutants that the test case kill
    - the number of mutants that the test case kill (is high good? why/why not? vise versa)
- find two equivalent mutants and justify why they are equivalent.

Ideas for lab verification:
- currently the lab at [TDDD04](https://www.ida.liu.se/~TDDD04/labs/2018/unit_testing/) says that the student should provide a screenshot that the test suite passes. This could probably be changed to the students opening a pull request to the lab assistant github project. A CI server could then automatically trigger and verify the students results.

**Comment by joakim-brannstrom** [comment]
@peatersson @JKRT

**Comment by joakim-brannstrom** [comment]
Ideas for the lab assignment

**Comment by joakim-brannstrom** [comment]
Ideas for the lab assignment:

**Comment by JKRT** [comment]
@joakim-brannstrom two points. 

> currently the lab at TDDD04 says that the student should provide a screenshot that the test suite passes. This could probably be changed to the students opening a pull request to the lab assistant github project. A CI server could then automatically trigger and verify the students results.

Not this year. However, it could be a nice extension, however
also, for the labs we use Gitlab : )

**Comment by JKRT** [comment]
I am damaged by writing to students. I guess I write verify findings a lot..

**Comment by peatersson** [comment]
The assignments are updated (but not finished) in https://github.com/peatersson/mutate-lab/blob/master/LAB_MASTER.md. Some changes were made to the layout for the lab, but with the consent of @JKRT. More detailed instructions and update of README's have also been done in the same repository.

This issue could be closed when both @joakim-brannstrom, @christoffer-nylen and @JKRT have reviewed and accepted the changes.

**Comment by JKRT** [comment]
Accepted!

**Comment by JKRT** [comment]
@joakim-brannstrom @peatersson @christoffer-nylen
