### ISSUE TITLE
mutate report: reduce summary text

### ISSUE THREAD

**Issue by christoffer-nylen** [joakim-brannstrom/dextool#906]
**Suggested changes to the summary print:**

From:

# Mutation Type lcr, lcrb, dcr, aor, sdl, rorp, cor

## Summary

```
Predicted time until mutation testing is done: 3 days, 4 hours, 52 minutes, 41 secs, 945 ms, 793 μs, and 1 hnsec (2019-Sep-15 12:43:40.7968267)
Mutation execution time:         1 day, 16 hours, 22 minutes, 25 secs, and 442 ms

Untested: 457
Score:   0.692
Alive:   74
Killed:  166
Timeout: 0
Total:   240
Killed by compiler: 0
```

To:

# Mutation Type lcr, lcrb, dcr, aor, sdl, rorp, cor

## Summary

```
Time spent: 1 day, 16 hours, 22 minutes, 25 secs
Remaining: 3 days, 4 hours, 52 minutes, 41 secs (2019-Sep-15 12:43:40)

Total:    697
Untested: 457
Score:    0.692
Alive:    74
Killed:   166
Timeout:  0
```

Notes:
* ms, μs, hnsecs is removed.
* total = untested + alive + killed + timeout
* `Killed by compiler:` is non-default information.

**Comment by christoffer-nylen** [comment]
> why no timeout?

Ops! My mistake. Yes, it should be `+ timeout` also.

**Comment by joakim-brannstrom** [comment]
I do not fully agree with the order. I want them to be in priority. The contention here is that I consider the score the most important fact thus it should be at the top.

**Comment by joakim-brannstrom** [comment]
```
Score:    0.692
Total:    697
Untested: 457
Alive:    74
Killed:   166
Timeout:  0
```

**Comment by joakim-brannstrom** [comment]
The other one is total. It is what has been used to calculate the mutation score. Untested are never part of that calculation thus untested can't be part of the total.

**Comment by joakim-brannstrom** [comment]
by keeping untested out of the calculation it also become possible to calculate a predicted mutation score with a confidence interval in the future.

untested should be seen as something that indicate it isn't finished. a "finished" report never have any untested in them so is then never a "problem". it is an intermediary state that the report is in.
