### ISSUE TITLE
mutate: add sanity check for build system failure

### ISSUE THREAD

**Issue by christoffer-nylen** [joakim-brannstrom/dextool#908]
**Assume:**
* There's a script `build.py` that builds the SUT and test binary.
* There's a script `test.py` that runs all tests for the SUT.
* The `build.py` script incorrectly returns `0` when there are compile errors.
* The `test.py` script returns `1` when the test binary is not found.
* The SUT contains many mutants that don't compile.

**Problem:**
The mutation score gets skewed due to compile errors being incorrectly regarded as "killed mutants".

**Suggestion:**
Add a sanity check to ensure that the provided `build.sh` script correctly returns a non-zero exit code in case of building errors.

**Comment by joakim-brannstrom** [comment]
Adding this sanity check is not planned. It is left to the user to ensure that failing to build the source code not returns zero. This will only be a problem for those that use custom build systems which contains bugs.
