### ISSUE TITLE
Some possible issue with the game example

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#909]
I have some issues running the game examples. 

It seems to be some kind of library issue, do you know what this can be about @joakim-brannstrom 

```
info: Using /home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/dextool_mutate.sqlite3
info: Reading compilation database:
/home/myUserCourses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/build/compile_commands.json
info: Analyze and mutation of files will only be done on those inside this directory root
info:   User input: .
info:   Real path: /home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial
info: Further restricted to those inside these paths
info:   User input: src
info:   Real path: /home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/src
info: Analyzing '/home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/test/basic.cpp'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:41:10: error: use of undeclared identifier '__builtin_ia32_bsrsi'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:104:1: error: definition of builtin function '__rdtsc'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:122:10: error: use of undeclared identifier '__builtin_ia32_rolqi'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:130:10: error: use of undeclared identifier '__builtin_ia32_rolhi'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:146:10: error: use of undeclared identifier '__builtin_ia32_rorqi'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:154:10: error: use of undeclared identifier '__builtin_ia32_rorhi'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/ia32intrin.h:187:10: error: use of undeclared identifier '__builtin_ia32_bsrdi'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:127:19: error: use of undeclared identifier '__builtin_ia32_addss'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:133:19: error: use of undeclared identifier '__builtin_ia32_subss'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:139:19: error: use of undeclared identifier '__builtin_ia32_mulss'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:145:19: error: use of undeclared identifier '__builtin_ia32_divss'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:239:10: error: use of undeclared identifier '__builtin_ia32_andps'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:245:10: error: use of undeclared identifier '__builtin_ia32_andnps'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:251:10: error: use of undeclared identifier '__builtin_ia32_orps'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:257:10: error: use of undeclared identifier '__builtin_ia32_xorps'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:285:19: error: use of undeclared identifier '__builtin_ia32_movss'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:295:19: error: use of undeclared identifier '__builtin_ia32_movss'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:323:19: error: use of undeclared identifier '__builtin_ia32_movss'
error: /usr/lib/gcc/x86_64-linux-gnu/5/include/xmmintrin.h:333:19: error: use of undeclared identifier '__builtin_ia32_movss'
error: fatal error: too many errors emitted, stopping now [-ferror-limit=]
error: Compile error...
```

Best regards, 

John

**Comment by joakim-brannstrom** [comment]
Yes two sec

**Comment by joakim-brannstrom** [comment]
the clang frontend is used to analyze the source code. This basically mean that dextool *compile* the code with clang.
What you are seeing is the same issue as happens when trying to compile a program with clang instead of c++.
clang (dextool via clang) by default try to inspect the host compiler and derived the includes from it.
but older versions of gcc have a c++stdlib that isn't compatible with clang.
To workaround this there is a configuration option where you can redirect dextool to a newer gcc compiler which hopefully have a newer version of the c++stdlib which in turn is compatible with clang++.
```toml
[compiler]
# use this compilers system includes instead of the one used in the compile_commands.json
# use_compiler_system_includes = "/path/to/c++"
```

I know that gcc-8 at least has a compatible c++stdlib

**Comment by JKRT** [comment]
@joakim-brannstrom  thank you for a prompt reply

Like this: 

`use_compiler_system_includes = "/usr/bin/gcc-8"`

**Comment by JKRT** [comment]
I did so and now 

I get 

error: /home/myUser/Courses/DEXTOOL/dextool/vendor/fused_gmock/gtest/gtest.h:54:10: fatal error: 'limits' file not found
error: Compile error...
.................. <--- More errors

Sorry for spamming I could probably figure it out on my own. Men nu glider jag helst lite pa annans kunnande

**Comment by joakim-brannstrom** [comment]
Try changing to `/usr/bin/g++-8`. I namely *think* it derived the information from the compiler for a C code, not C++ code.

**Comment by joakim-brannstrom** [comment]
The option should be extended and improved in the future to allow a "mapping" from one compiler to another but I just haven't seen the need because this is only needed as a workaround for ancient systems ;)

**Comment by JKRT** [comment]
I will instead g++-8 and point to that instead of gcc-8

**Comment by JKRT** [comment]
Works like a charm. As you said, it might be good to add this to common problems

**Comment by JKRT** [comment]
Ok. 

I was to optimistic. For the second example with lcr I get the following error: 

[ 92%] Building CXX object CMakeFiles/rl_test.dir/src/window.cpp.o
In file included from /home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/src/event.h:7:0,
                 from /home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/src/system.h:4,
                 from /home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/src/physicssystem.h:13,
                 from /home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/src/physicssystem.cpp:1:
/home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/deps/variant.h: In member function ‘const T& Variant<Ts>::get() const’:
/home/myUser/Courses/DEXTOOL/dextool/plugin/mutate/examples/game_tutorial/deps/variant.h:198:15: error: ‘bad_cast’ is not a member of ‘std’
         throw std::bad_cast{};

**Comment by joakim-brannstrom** [comment]
try compiling with verbose on to see what flags are used to compile window.cpp
```
make VERBOSE=1
```

This flag must be found `-std=c++14` or it wont work at all. maybe it should be 17? hmm

**Comment by joakim-brannstrom** [comment]
Maybe cmake is using the *ancient* compiler when compiling the project hmm.

**Comment by JKRT** [comment]
Your suggestion solved it. Now I have this problem:

```
CMAKE_CXX_COMPILER= /usr/bin/g++-8

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:24 (add_library):
  Cannot find source file:

    //gmock-gtest-all.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:24 (add_library):
  No SOURCES given to target: gtest
```

**Comment by joakim-brannstrom** [comment]
Hmm, did you by accident modify CMakeLists.txt?
Look in the script `setup.sh` and execute the cmake command inside your `build` directory exactly as it is in the script but plus the `-DCMAKE_CXX_COMPILER`.
CMakeLists.txt namely uses `GTEST_DIR` that is expected to be supplied by the user which point to the directory where gmock-gtest-all.cc is

**Comment by JKRT** [comment]
I do not think so. A sec, providing a diff

**Comment by JKRT** [comment]
```
diff --git a/plugin/mutate/examples/game_tutorial/.dextool_mutate.toml b/plugin/mutate/examples/game_tutorial/.dextool_mutate.toml
index 75f69a4..aaf45b1 100644
--- a/plugin/mutate/examples/game_tutorial/.dextool_mutate.toml
+++ b/plugin/mutate/examples/game_tutorial/.dextool_mutate.toml
@@ -17,7 +17,7 @@ restrict = [ "src" ]
 # toggle this to force system include paths to use -I instead of -isystem
 # force_system_includes = true
 # use this compilers system includes instead of the one used in the compile_commands.json
-# use_compiler_system_includes = "/path/to/c++"
+use_compiler_system_includes = "/usr/bin/g++-8"

 [compile_commands]
 # search for compile_commands.json in this paths
diff --git a/plugin/mutate/examples/game_tutorial/build.sh b/plugin/mutate/examples/game_tutorial/build.sh
index f0ad97a..338935b 100755
--- a/plugin/mutate/examples/game_tutorial/build.sh
+++ b/plugin/mutate/examples/game_tutorial/build.sh
@@ -1,2 +1,2 @@
 #!/bin/bash
-cd build && make -j $(nproc) rl_test
+cd build && make VERBOSE=1 -j $(nproc) rl_test
diff --git a/plugin/mutate/examples/game_tutorial/setup.sh b/plugin/mutate/examples/game_tutorial/setup.sh
index 8b34e87..47c27ed 100755
--- a/plugin/mutate/examples/game_tutorial/setup.sh
+++ b/plugin/mutate/examples/game_tutorial/setup.sh
@@ -2,7 +2,7 @@

 mkdir -p build
 pushd build
-cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DGTEST_DIR=../../../../vendor/fused_gmock
+cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DGTEST_DIR=../../../../vendor/fused_gmock -DCMAKE_CXX_COMPILER=/usr/bin/g++-8
 popd

 mkdir -p build_cov
```

**Comment by joakim-brannstrom** [comment]
that is so strange because the only way I can see that it would say `//gmock-gtest-all.cc` is if the variable GTEST_DIR where to be compressed to `//`

**Comment by joakim-brannstrom** [comment]
try rm -rf build and re-execute setup.sh.....

**Comment by joakim-brannstrom** [comment]
what distribution are you using? I could add it to the

**Comment by JKRT** [comment]
The corrupted build was the issue. restarting everything seemed to work

**Comment by joakim-brannstrom** [comment]
Thank you for your patience. I am glad it finally got working.

**Comment by JKRT** [comment]
Thank you!
