### ISSUE TITLE
Treemap seems to be work in progress. Maybe disable for now

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#911]
For me when I use the treemap I get a very distorted graphical overview. 

I think it might be good to disable it for now so that we do not confuse the students for the lab that was described #901 

![bild](https://user-images.githubusercontent.com/8775827/64926540-cfd4b700-d7fe-11e9-825c-1a149688d02e.png)

**Comment by joakim-brannstrom** [comment]
I agree. I'll hide it behind a toggle option like the others.

**Comment by peatersson** [comment]
I think it is better if we just remove it from the report for now. Or was that maybe what you meant?

**Comment by joakim-brannstrom** [comment]
By hiding it behind a flag, as many others are, it doesn't become part of the default
