### ISSUE TITLE
mutate: missing sdl mutant for return statements in void functions

### ISSUE THREAD

**Issue by christoffer-nylen** [joakim-brannstrom/dextool#918]
I have code that looks something like this:
```
122: void createStuff() {
...
138:   if (numCreated >= MAX)
139:     *result = INVALID_NUM;
140:     return;
141:   }
142:
143:   if (id == null){
144:     *result = INVALID_ID;
145:     return;
146:   }
147:
148:   *result = OK;
149: }
```

I used the `sdl` mutation operator and got the following html result:

Line 139 is red.
Line 140 is green.
Line 141 is green.

Line 144 is red.
Line 145 is green.
Line 146 is green.

Problem/bug:
* The list of test cases does not appear when selecting line 140 and 145.

Comment:
* I suspect line 140 and 145 is green due to function body deletion but single-line mutants is not generated for `return;` statements?

**Comment by joakim-brannstrom** [comment]
solved
