### ISSUE TITLE
Link to the description of what the different flags mean in the game tutorial for dextool

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#928]
Hi, 

I got the following comments regarding the lab. We should have a link in the game tutorial in plugins/examples/gametutorial that links to information regarding what the different flags mean

**Comment by joakim-brannstrom** [comment]
I agree. Time to write it.....

**Comment by peatersson** [comment]
Description added and available in [options.md](https://github.com/joakim-brannstrom/dextool/blob/master/plugin/mutate/doc/design/options.md).
