### ISSUE TITLE
Provide a stable branch 

### ISSUE THREAD

**Issue by JKRT** [joakim-brannstrom/dextool#937]
Hi! 

It has come to my attention that there are quite a lot of changes occuring on master from time to time. Since you guys now have LiU as an external dependency I would like you to introduce a stable branch which you only merge to when there is a release, that would make testing easier from our side. 

An alternative to that would be to have a develop branch and only merge into master when there are releases and everything is tested to make sure that it works for external users 

@joakim-brannstrom 

Best regards,

John

**Comment by joakim-brannstrom** [comment]
Hi,

I understand your concern.
The problem that you state is "how to ensure that the students can complete the lab with minimal disruptions"?

My proposal is to do as commonly is done by releasing a stable version via a git tag. Master keep on being "in flux". New tags are released in the future and Liu can update the version that is used in the lab as seen fit.

If there ever are a critical bug that must be fixed we can do a release branch and a point release.

The one that is HEAD now in master is tagged as the next release that you use. From the report I got it has worked pretty well so far :)

What do you think of the above?

**Comment by JKRT** [comment]
All OK, 👍  I'll close it

**Comment by joakim-brannstrom** [comment]
For you, @JKRT 

[Liu Stable](https://github.com/joakim-brannstrom/dextool/releases/tag/v1.3.2)
