### ISSUE TITLE
Progress indication

### ISSUE THREAD

**Issue by joakim-brannstrom-work1** [joakim-brannstrom/dextool#939]
**Problem**: The user run dextool mutate test and is wondering how much is left.
This becomes a problem when the mutation testing e.g. "hogg" one/many of the build slaves and the user needs to know if it is 20min left and he/she should just let it finish or 1 day.

**Solution**:
Allow the user to configure a max time that dextool mutate test is running. This allows a user to have it persist on a CI server and have a progress e.g. each night until all mutants are tested.

The report that then is produced will show how much time is left until all mutants are tested.

Such a feature can be reused for a "fast mode" for testing mutants on a pull request by *just* shortening the time to e.g 5 minutes.

**Comment by peatersson** [comment]
This could be fixed quite easily. If we add an option in the conflig-file, and it is set, it should only be to "wrap" the _runTester_ in _plugin/mutate/backend/test_mutant/_ ?

**Comment by joakim-brannstrom** [comment]
#943 partially solved this by allowing the user to "stop" and thus get a partial report.

**Comment by joakim-brannstrom** [comment]
Seems to be good enough for now.
