### ISSUE TITLE
Roadmap for Q4/2020 Q1

### ISSUE THREAD

**Issue by joakim-brannstrom** [joakim-brannstrom/dextool#941]
**Problem**: We have no public roadmap for dextool and specifically mutate which make it hard for others to understand what we are doing internally and what our long term plans are.
It actually make it a bit hard for me to share the information, get feedback and evolve the plan.

**Solution**: Publish a six month plan.

**Comment by peatersson** [comment]
Ref it from README before "Getting started", so that users/interested parties/developers see it easily?
