### ISSUE TITLE
Parallel Execution

### ISSUE THREAD

**Issue by borgmanJeremy** [joakim-brannstrom/dextool#971]
The README mentions parallel execution is possible if the same source code is not mutated, but does not list an example or best practice.

Is the best way to have multiple versions of .dextool_mutate.toml and restrict it to a subset of the source code?

**Comment by joakim-brannstrom** [comment]
Thank you for the question. This is what is needed to slowely but surely improve the documentation. I made a pull request to add an example and expand the explanation, #972 . Does that answer your question for what is best practise?
I have used this approach over a year and it seems to work well :)

**Comment by borgmanJeremy** [comment]
Yeah this is great! It should really speed up the run time.

By the way this project is great. It was well documented and pretty easy to integrate into a cmake project. The only other thing that I think could use more documentation is the definition of the mutation acronyms (AOR, ROR, DCC, DCR, LCR, COR, SDL) I was able to google around to understand what most of them did, but it would be handy to have it documented here with some examples of what it does to the c++ code. It becomes pretty clear once you generate the html report so its not too critical.

Thanks again.

**Comment by joakim-brannstrom** [comment]
Thank you. We'll see to it that the documentation for the operators is improved and a guide with rational for what operators to use based on our experience and empirical evidence :)
