### ISSUE TITLE
Equivalent mutant detections

### ISSUE THREAD

**Issue by joakim-brannstrom** [joakim-brannstrom/dextool#997]
The paper "Evaluation of Mutation Testing in a Nuclear Industry Case Study" describe how Trivial Compiler Equivalence can be used to reduce the cost of using mutation testing by removing invalid, equivalent or duplicate mutants.

The tool and library [alive2](https://github.com/AliveToolkit/alive2) contains a the tool **alive-tv** which can compare two llvm bitcodes for equivalens.

We should experiment with alive2 to see if it is possible to use it and how for mutation testing.

**Comment by christoffer-nylen** [comment]
It has been implemented here also: https://github.com/thierry-tct/mart/tree/master/lib

**Comment by christoffer-nylen** [comment]
Some more links:
* http://pages.cs.aueb.gr/~mpapad/papers/ICSE15B.pdf
* https://orbilu.uni.lu/bitstream/10993/39780/3/main.pdf

**Comment by christoffer-nylen** [comment]
Summary:
> Our results reveal that, on large real-world programs, **TCE can discard more than 7% and 21% of all the mutants** as being equivalent and duplicated mutants respectively. A humanbased equivalence verification reveals that TCE has the ability to detect approximately 30% of all the existing equivalent mutants

Details:

![image](https://user-images.githubusercontent.com/5559216/72221153-142b5600-3558-11ea-9ee0-94cdfaac9957.png)

**Comment by christoffer-nylen** [comment]
Example:

```c++
for(i=0; i<SOMETHING; i = i + 1)
vs
for(i=0; i!=SOMETHING; i = i + 1)
```

**Comment by christoffer-nylen** [comment]
An example of defensive programming:

```
switch( c ) {
case RED:
  DoStuff();
  break;
case GREEN: // Statement deletion -> Equivalent mutant
  break;
  ...
default:
  break;
}
´´´

**Comment by joakim-brannstrom** [comment]
yeppeti yo, we need it. manual pattern detection only go so far. The one with for- and switch-statement though is such a common that we'll implement it to get an immediate improvement

**Comment by christoffer-nylen** [comment]
Another example:

```
while(TRUE)
```
->
```
while(1)
```

**Comment by joakim-brannstrom** [comment]
That one I am thinking of adding a discarder that remove a mutant if it is textural equivalent.

**Comment by joakim-brannstrom** [comment]
A simple variant of TCE is implemented which uses checksums of test binaries. The advanced version of comparing the LLVM IR of original and mutant is not planned to be added in a forceable future.
